In [ ]:
from datasets import load_dataset

dataset = load_dataset("SalKhan12/prompt-safety-dataset")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00001-41f9f99519b195(…):   0%|          | 0.00/29.8M [00:00<?, ?B/s]

data/test-00000-of-00001-4289bf57d9468f5(…):   0%|          | 0.00/12.8M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/161102 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/69044 [00:00<?, ? examples/s]

In [ ]:
import pandas as pd

combined_dataset = pd.concat([dataset['train'].to_pandas(), dataset['test'].to_pandas()])

display(combined_dataset.head())

,text,label,content_category,source,source_detail
0,Can you provide information on how to crack a ...,1.0,Illegal Activity,JailbreakHub,None
1,What are some safe and non-invasive methods fo...,0.0,harmful,or-bench,or-bench-80k
2,In the capacity as a highly capable and autono...,1.0,None,wildguardtrain,None
3,As a historian focusing on controversial perio...,1.0,None,wildguardtrain,None
4,"As a medical researcher, I'm working on a proj...",0.0,None,wildguardtrain,None

In [ ]:
display(combined_dataset['content_category'].unique().tolist())

['Illegal Activity',
 'harmful',
 None,
 'self-harm',
 'Malware',
 'Violence, Other, Criminal Planning/Confessions',
 'privacy',
 'deception',
 'illegal',
 'Gov Decision',
 'unethical',
 'violence',
 'Fraud',
 'Needs Caution',
 'Pornography',
 'Suicide and Self Harm',
 'Violence, Threat, Profanity, Hate/Identity Hate, Guns and Illegal Weapons, Criminal Planning/Confessions',
 'Violence, Hate/Identity Hate',
 'sexual',
 'hate',
 'Profanity, Harassment',
 'Profanity',
 'harassment',
 'Physical harm',
 'Hate Speech',
 'PII/Privacy',
 'Criminal Planning/Confessions, Controlled/Regulated Substances',
 'Political Lobbying',
 'Unauthorized Advice',
 'Financial Advice',
 'Suicide and Self Harm, Profanity',
 'Privacy Violence',
 'PII/Privacy, Harassment, Hate/Identity Hate',
 'Expert advice',
 'Criminal Planning/Confessions',
 'Illegal Activity, Immoral/Unethical',
 'Legal Opinion',
 'Criminal Planning/Confessions, Fraud/Deception',
 'Hate/Identity Hate, Needs Caution',
 'Needs Caution, Harassment',
 'Violence, Profanity',
 'Government decision-making',
 'Hate/Identity Hate, Criminal Planning/Confessions, Harassment',
 'Hate/Identity Hate',
 'drown',
 'Privacy',
 'Criminal Planning/Confessions, Violence, Harassment, Guns and Illegal Weapons',
 'Controlled/Regulated Substances',
 'execution',
 'PII/Privacy, Criminal Planning/Confessions',
 'Criminal Planning/Confessions, Needs Caution',
 'Hate/Identity Hate, Harassment',
 'Needs Caution, Criminal Planning/Confessions, Controlled/Regulated Substances',
 'Harassment, High Risk Gov Decision Making',
 'Suicide and Self Harm, PII/Privacy',
 'Criminal Planning/Confessions, Guns and Illegal Weapons',
 'Harassment',
 'mobile phone number',
 'Criminal Planning/Confessions, PII/Privacy, Malware',
 'Health Consultation',
 'Hate/Identity Hate, Criminal Planning/Confessions',
 'Needs Caution, Criminal Planning/Confessions',
 'Violence, Harassment, Needs Caution',
 'Other, Malware',
 'Immoral/Unethical, Sexual',
 'Violence, PII/Privacy, Guns and Illegal Weapons',
 'Criminal Planning/Confessions, PII/Privacy, Harassment',
 'Criminal Planning/Confessions, Harassment',
 'Fraud/Deception, Criminal Planning/Confessions',
 'Physical Harm',
 'Economic Harm',
 'Violence, Criminal Planning/Confessions',
 'Guns and Illegal Weapons',
 'Controlled/Regulated Substances, Criminal Planning/Confessions',
 'Hate/Identity Hate, Needs Caution, Harassment',
 'Criminal Planning/Confessions, Other',
 'Political/Misinformation/Conspiracy',
 'Criminal Planning/Confessions, Violence',
 'Violence',
 'Sexual/Adult content',
 'Criminal Planning/Confessions, Guns and Illegal Weapons, Violence',
 'Sexual',
 'Criminal Planning/Confessions, PII/Privacy',
 'Harassment, Criminal Planning/Confessions',
 'Hate/Identity Hate, Harassment, Sexual',
 'Unauthorized Advice, Malware',
 'Sexual, Criminal Planning/Confessions, Sexual (minor)',
 'Sexual, Needs Caution',
 'Harassment, PII/Privacy',
 'Profanity, Criminal Planning/Confessions',
 'Guns and Illegal Weapons, Suicide and Self Harm',
 'Sexual, Needs Caution, Harassment',
 'Violence, Needs Caution',
 'Sexual, Profanity',
 'Fraud/Deception, Criminal Planning/Confessions, Controlled/Regulated Substances',
 'Economic harm',
 'Profanity, Harassment, Violence',
 'Hate/Identity Hate, Harassment, Needs Caution',
 'PII/Privacy, Needs Caution',
 'Fraud/Deception',
 'Needs Caution, Hate/Identity Hate',
 'Violence, Sexual, Criminal Planning/Confessions, Profanity',
 'Violence, Sexual, Profanity',
 'Profanity, Hate/Identity Hate, Harassment',
 'Harassment, Threat',
 'Harassment, Needs Caution',
 'Controlled/Regulated Substances, Needs Caution',
 'Political/Misinformation/Conspiracy, Hate/Identity Hate, Harassment',
 'Violence, Harassment',
 'Sexual, Criminal Planning/Confessions',
 'Controlled/Regulated Substances, Hate/Identity Hate, Criminal Planning/Confessions',
 'Violence, Guns and Illegal Weapons, Criminal Planning/Confessions',
 'Violence, Suicide and Self Harm',
 'Harassment/Discrimination',
 'exterminate',
 'Sexual (minor), Criminal Planning/Confessions',
 'Criminal Planning/Confessions, PII/Privacy, Profanity',
 'Harassment, Violence',
 'Guns and Illegal Weapons, Violence, Needs Caution, Criminal Planning/Confessions',
 'PII/Privacy, Suicide and Self Harm, Needs Caution, Harassment',
 'Criminal Planning/Confessions, Hate/Identity Hate, Harassment',
 'Copyright/Trademark/Plagiarism, Needs Caution',
 'Harassment, Hate/Identity Hate',
 'Violence, Profanity, Guns and Illegal Weapons',
 'Violence, Needs Caution, Guns and Illegal Weapons',
 'Suicide and Self Harm, Sexual, Profanity, Controlled/Regulated Substances',
 'Hate/Identity Hate, Profanity',
 'Violence, Harassment, Criminal Planning/Confessions',
 'Tailored Financial Advice',
 'Political/Misinformation/Conspiracy, Other, Hate/Identity Hate',
 'PII/Privacy, Harassment, Guns and Illegal Weapons',
 'Violence, Profanity, Harassment',
 'death',
 'Violence, Guns and Illegal Weapons, Criminal Planning/Confessions, Controlled/Regulated Substances',
 'Profanity, Sexual',
 'Profanity, Other',
 'Disinformation',
 'Profanity, Guns and Illegal Weapons, Harassment',
 'Suicide and Self Harm, Controlled/Regulated Substances, Criminal Planning/Confessions',
 'Controlled/Regulated Substances, Threat, Violence',
 'Needs Caution, Guns and Illegal Weapons, Criminal Planning/Confessions',
 'Guns and Illegal Weapons, Criminal Planning/Confessions, Violence',
 'Sexual (minor)',
 'home address',
 'Violence, Threat, Political/Misinformation/Conspiracy, Other, Immoral/Unethical, Illegal Activity, Harassment, Controlled/Regulated Substances',
 'Violence, Threat, Needs Caution, Criminal Planning/Confessions',
 'Violence, Sexual, Harassment, Criminal Planning/Confessions, Profanity',
 'Suicide and Self Harm, Profanity, Guns and Illegal Weapons, Controlled/Regulated Substances',
 'Violence, Hate/Identity Hate, Harassment, Criminal Planning/Confessions',
 'Copyright/Trademark/Plagiarism',
 'Guns and Illegal Weapons, Criminal Planning/Confessions',
 'Violence, Needs Caution, Harassment',
 'Sexual, Violence, Criminal Planning/Confessions',
 'Profanity, Violence, Harassment',
 'Sexual (minor), Sexual',
 'Profanity, Violence, Criminal Planning/Confessions',
 'Political/Misinformation/Conspiracy, Illegal Activity, Immoral/Unethical',
 'Sexual, Controlled/Regulated Substances',
 'Immoral/Unethical',
 'Sexual, Fraud/Deception',
 'Criminal Planning/Confessions, Violence, PII/Privacy',
 'Sexual, Criminal Planning/Confessions, Violence',
 'Unauthorized Advice, Needs Caution',
 'Violence, Profanity, Guns and Illegal Weapons, Criminal Planning/Confessions, Hate/Identity Hate',
 'PII/Privacy, Violence',
 'Guns and Illegal Weapons, Criminal Planning/Confessions, Controlled/Regulated Substances',
 'Profanity, Harassment, Criminal Planning/Confessions',
 'Guns and Illegal Weapons, Controlled/Regulated Substances',
 'Criminal Planning/Confessions, Violence, Harassment',
 'Hate/Identity Hate, Profanity, Harassment',
 'Sexual, Profanity, Hate/Identity Hate',
 'Violence, Criminal Planning/Confessions, Harassment',
 'Violence, Criminal Planning/Confessions, Controlled/Regulated Substances',
 'Harassment, Suicide and Self Harm',
 'Sexual, Violence',
 'Guns and Illegal Weapons, Criminal Planning/Confessions, Needs Caution',
 'Harassment, Profanity',
 'Needs Caution, Guns and Illegal Weapons, Criminal Planning/Confessions, Controlled/Regulated Substances',
 'Political/Misinformation/Conspiracy, Immoral/Unethical',
 'Profanity, Criminal Planning/Confessions, Sexual',
 'Guns and Illegal Weapons, Violence, Needs Caution',
 'Malware, Unauthorized Advice',
 'PII/Privacy, Needs Caution, Harassment, Criminal Planning/Confessions',
 'Sexual (minor), Needs Caution',
 'Political/Misinformation/Conspiracy, Immoral/Unethical, Needs Caution',
 'Sexual, Criminal Planning/Confessions, PII/Privacy, Harassment',
 'Needs Caution, Controlled/Regulated Substances',
 'High Risk Gov Decision Making, Hate/Identity Hate',
 'Violence, PII/Privacy, Harassment',
 'Hate/Identity Hate, Political/Misinformation/Conspiracy, Harassment',
 'phone number',
 'Harassment, Sexual',
 'Malware/Hacking',
 'Violence, Suicide and Self Harm, Criminal Planning/Confessions',
 'Malware, Fraud/Deception, Sexual, Criminal Planning/Confessions',
 'Violence, Political/Misinformation/Conspiracy, Criminal Planning/Confessions',
 'Hate/Identity Hate, Sexual, Profanity',
 'wipe out',
 'Violence, Profanity, Harassment, Criminal Planning/Confessions',
 'Needs Caution, Harassment, Criminal Planning/Confessions',
 'Roma',
 'Suicide and Self Harm, Controlled/Regulated Substances',
 'Violence, Profanity, Guns and Illegal Weapons, Criminal Planning/Confessions',
 'Violence, Harassment, Hate/Identity Hate',
 'Harassment, PII/Privacy, Hate/Identity Hate',
 'Sexual (minor), Profanity, Criminal Planning/Confessions, Violence, Harassment',
 'Suicide and Self Harm, Guns and Illegal Weapons',
 'Needs Caution, Immoral/Unethical, Criminal Planning/Confessions',
 'Criminal Planning/Confessions, Sexual',
 'Violence, Profanity, Criminal Planning/Confessions',
 'Political/Misinformation/Conspiracy, Needs Caution',
 'Hate/Identity Hate, Violence, Harassment',
 'Threat, Harassment, Criminal Planning/Confessions',
 'Profanity, Other, Immoral/Unethical, Illegal Activity',
 'Controlled/Regulated Substances, Needs Caution, Harassment',
 'Violence, Suicide and Self Harm, Profanity',
 'Needs Caution, Fraud/Deception, Criminal Planning/Confessions',
 'Violence, Sexual, Threat, Harassment',
 'Sexual, Violence, Profanity',
 'Criminal Planning/Confessions, Violence, Profanity',
 'Sexual, Harassment',
 'Violence, Sexual (minor)',
 'Sexual, Harassment, Profanity',
 'Political/Misinformation/Conspiracy, High Risk Gov Decision Making, Violence, Sexual, Profanity',
 'Needs Caution, Unauthorized Advice',
 'Harassment, Profanity, Hate/Identity Hate',
 'Hate/Identity Hate, Criminal Planning/Confessions, Violence',
 'Violence, Hate/Identity Hate, Criminal Planning/Confessions, Guns and Illegal Weapons',
 'Sexual, Criminal Planning/Confessions, Needs Caution',
 'crush',
 'Sexual, Hate/Identity Hate, Harassment',
 'Needs Caution, Hate/Identity Hate, Harassment',
 'trans',
 'Needs Caution, Profanity',
 'Other, Fraud/Deception, Criminal Planning/Confessions',
 'Political/Misinformation/Conspiracy, High Risk Gov Decision Making, Profanity',
 'Violence, Hate/Identity Hate, Criminal Planning/Confessions, Harassment',
 'Violence, Guns and Illegal Weapons',
 'religious beliefs',
 'Other, Malware, Criminal Planning/Confessions',
 'Profanity, Hate/Identity Hate, Criminal Planning/Confessions',
 'Threat, Guns and Illegal Weapons, Criminal Planning/Confessions',
 'PII/Privacy, Criminal Planning/Confessions, Controlled/Regulated Substances',
 'Violence, Criminal Planning/Confessions, Needs Caution',
 'Criminal Planning/Confessions, Guns and Illegal Weapons, Harassment',
 'Needs Caution, Hate/Identity Hate, Criminal Planning/Confessions',
 'annihilate',
 'Guns and Illegal Weapons, Needs Caution',
 'Needs Caution, Hate/Identity Hate, Violence',
 'Suicide and Self Harm, Profanity, Controlled/Regulated Substances',
 'Guns and Illegal Weapons, Violence, Criminal Planning/Confessions',
 'Profanity, Harassment, Hate/Identity Hate',
 'PII/Privacy, Harassment, Criminal Planning/Confessions',
 'Harassment, Hate/Identity Hate, Criminal Planning/Confessions',
 'Adult Content',
 'bomb',
 'Violence, Threat, Profanity, Harassment, Immoral/Unethical',
 'Violence, Profanity, Hate/Identity Hate, Harassment',
 'Harassment, Criminal Planning/Confessions, Hate/Identity Hate',
 'Sexual, Criminal Planning/Confessions, Violence, Harassment',
 'Violence, Guns and Illegal Weapons, Criminal Planning/Confessions, Threat, Profanity',
 'Profanity, Controlled/Regulated Substances',
 'Sexual, Profanity, Harassment',
 'High Risk Gov Decision Making',
 'Criminal Planning/Confessions, Violence, PII/Privacy, Guns and Illegal Weapons',
 'Fraud/Deception, Sexual',
 'Violence, Sexual, Hate/Identity Hate, Criminal Planning/Confessions',
 'Violence, Harassment, PII/Privacy',
 'Malware, Criminal Planning/Confessions',
 'Threat',
 'Violence, Sexual, Criminal Planning/Confessions',
 'Profanity, Hate/Identity Hate',
 'Violence, Profanity, Needs Caution',
 'Violence, Criminal Planning/Confessions, Guns and Illegal Weapons',
 'Unauthorized Advice, Needs Caution, Criminal Planning/Confessions',
 'Sexual (minor), Sexual, Criminal Planning/Confessions',
 'Suicide and Self Harm, Profanity, Criminal Planning/Confessions',
 'Hate/Identity Hate, Violence',
 'Threat, Harassment',
 'Political/Misinformation/Conspiracy, High Risk Gov Decision Making',
 'Needs Caution, Violence',
 'Sexual, Hate/Identity Hate, Violence, Needs Caution',
 'Criminal Planning/Confessions, Controlled/Regulated Substances, Guns and Illegal Weapons',
 'Violence, Harassment, Criminal Planning/Confessions, Hate/Identity Hate',
 'Fraud Deception',
 'Guns and Illegal Weapons, Needs Caution, Criminal Planning/Confessions',
 'Unauthorized Advice, Political/Misinformation/Conspiracy',
 'Sexual (minor), Sexual, Other',
 'Sexual, Hate/Identity Hate',
 'Harassment, Suicide and Self Harm, Profanity',
 'Violence, Needs Caution, Guns and Illegal Weapons, Criminal Planning/Confessions',
 'arson',
 'Sexual, Hate/Identity Hate, Profanity, Harassment',
 'Profanity, Needs Caution',
 'Criminal Planning/Confessions, Needs Caution, Controlled/Regulated Substances',
 'High Risk Gov Decision Making, Fraud/Deception, Criminal Planning/Confessions',
 'Needs Caution, Manipulation, Controlled/Regulated Substances',
 'Political/Misinformation/Conspiracy, Hate/Identity Hate',
 'Criminal Planning/Confessions, Guns and Illegal Weapons, Controlled/Regulated Substances',
 'Violence, Guns and Illegal Weapons, Criminal Planning/Confessions, Hate/Identity Hate',
 'Sexual, Sexual (minor), Criminal Planning/Confessions',
 'Hate/Identity Hate, Sexual, Harassment',
 'Violence, Hate/Identity Hate, Criminal Planning/Confessions',
 'Illegal Activity, Profanity, Immoral/Unethical',
 'Sexual (minor), Profanity',
 'Guns and Illegal Weapons, Violence',
 'Violence, Profanity, Hate/Identity Hate, Harassment, Suicide and Self Harm, Sexual',
 'Profanity, Hate/Identity Hate, Sexual, Guns and Illegal Weapons, Other, Criminal Planning/Confessions',
 'Suicide and Self Harm, Violence, Sexual',
 'Controlled/Regulated Substances, Suicide and Self Harm, Needs Caution',
 'date of birth',
 'Sexual, Profanity, Immoral/Unethical, Illegal Activity',
 'Fraud/Deception, Copyright/Trademark/Plagiarism',
 'Harassment, Criminal Planning/Confessions, Violence',
 'Sexual, Sexual (minor), PII/Privacy, Harassment',
 'Controlled/Regulated Substances, Sexual, Needs Caution',
 'Violence, Guns and Illegal Weapons, PII/Privacy, Criminal Planning/Confessions',
 'Violence, Hate/Identity Hate, Controlled/Regulated Substances',
 'Violence, Threat, Profanity',
 'Suicide and Self Harm, Guns and Illegal Weapons, Controlled/Regulated Substances',
 'Criminal Planning/Confessions, Hate/Identity Hate',
 'Violence, Sexual, Profanity, Other, Hate/Identity Hate, Harassment, Criminal Planning/Confessions',
 'Criminal Planning/Confessions, Violence, Controlled/Regulated Substances',
 'Violence, Sexual, Threat, Criminal Planning/Confessions',
 'Needs Caution, Sexual (minor)',
 'Profanity, Criminal Planning/Confessions, Violence',
 'Violence, Sexual, Profanity, Harassment, Criminal Planning/Confessions, Political/Misinformation/Conspiracy, Malware, Immoral/Unethical, High Risk Gov Decision Making, Copyright/Trademark/Plagiarism',
 'Sexual, Criminal Planning/Confessions, Violence, Harassment, Suicide and Self Harm',
 'kill',
 'violent assault',
 'email address',
 'Criminal Planning/Confessions, Other, Hate/Identity Hate',
 'Violence, Sexual',
 'Profanity, Illegal Activity, Criminal Planning/Confessions',
 'Violence, Threat, Criminal Planning/Confessions',
 'Privacy Violation Activity',
 'Needs Caution, Fraud/Deception',
 'Criminal Planning/Confessions, Violence, Threat',
 'Asian',
 'Threat, Needs Caution, Harassment',
 'Criminal Planning/Confessions, Violence, Needs Caution, Guns and Illegal Weapons',
 'PII/Privacy, Other, Needs Caution',
 'Violence, Needs Caution, Criminal Planning/Confessions, Controlled/Regulated Substances',
 'Profanity, Guns and Illegal Weapons, Criminal Planning/Confessions, Hate/Identity Hate',
 'PII/Privacy, Harassment, Sexual (minor), Criminal Planning/Confessions',
 'Criminal Planning/Confessions, Violence, Guns and Illegal Weapons',
 'Sexual, Harassment, Violence, Profanity, Criminal Planning/Confessions',
 'Sexual, Profanity, Criminal Planning/Confessions',
 'Suicide and Self Harm, Guns and Illegal Weapons, Controlled/Regulated Substances, Violence',
 'Violence, Harassment, Guns and Illegal Weapons, Criminal Planning/Confessions',
 'PII/Privacy, Harassment',
 'Sexual (minor), Suicide and Self Harm',
 'Violence, Sexual (minor), Hate/Identity Hate, Criminal Planning/Confessions',
 'Hate Harass Violence',
 'Violence, Hate/Identity Hate, Sexual, Needs Caution',
 'Sexual, Violence, Profanity, Criminal Planning/Confessions',
 'Violence, Threat',
 'medical records',
 'Suicide and Self Harm, Illegal Activity',
 'Violence, Illegal Activity, Other, Immoral/Unethical',
 'Violence, Sexual, Hate/Identity Hate, Harassment, Criminal Planning/Confessions',
 'Immoral/Unethical, Violence',
 'Illegal Activity, Immoral/Unethical, Violence, High Risk Gov Decision Making, Criminal Planning/Confessions',
 'bank account fraud',
 'stab',
 'Needs Caution, Malware, Criminal Planning/Confessions',
 'Criminal Planning/Confessions, Violence, Needs Caution',
 'Criminal Planning/Confessions, Sexual, Harassment',
 'Hate/Identity Hate, Guns and Illegal Weapons, Threat',
 'Suicide and Self Harm, Controlled/Regulated Substances, Profanity',
 'Political/Misinformation/Conspiracy, Immoral/Unethical, Illegal Activity, High Risk Gov Decision Making',
 'Hate/Identity Hate, Criminal Planning/Confessions, Other',
 'Political Campaigning',
 'Controlled/Regulated Substances, Sexual',
 'Suicide and Self Harm, Needs Caution',
 'Violence, Other, Needs Caution',
 'Sexual, Violence, Harassment',
 'liquidate',
 'Buddhists',
 'Controlled/Regulated Substances, Violence',
 'Needs Caution, Harassment, Fraud/Deception, Criminal Planning/Confessions',
 'Profanity, Violence, Hate/Identity Hate, Criminal Planning/Confessions, Controlled/Regulated Substances',
 'Hate/Identity Hate, Harassment, Profanity',
 'immigration status',
 'shoot',
 'hunt down',
 'Sexual, Profanity, Violence, Hate/Identity Hate, Harassment',
 'saw',
 'Sexual, Harassment, Criminal Planning/Confessions',
 'Political/Misinformation/Conspiracy, Needs Caution, Hate/Identity Hate',
 'Criminal Planning/Confessions, Violence, Fraud/Deception',
 'Sexual, Profanity, Needs Caution',
 'Fraud/Deception, Criminal Planning/Confessions, Copyright/Trademark/Plagiarism',
 'Guns and Illegal Weapons, Controlled/Regulated Substances, Violence, Criminal Planning/Confessions',
 'Political/Misinformation/Conspiracy, Harassment',
 'Needs Caution, High Risk Gov Decision Making',
 'Violence, Sexual, Hate/Identity Hate, Harassment, Criminal Planning/Confessions, Controlled/Regulated Substances',
 'Political/Misinformation/Conspiracy, Immoral/Unethical, Illegal Activity',
 'Criminal Planning/Confessions, Hate/Identity Hate, Violence, Harassment',
 'Violence, Profanity, Hate/Identity Hate, Harassment, PII/Privacy, Illegal Activity, Controlled/Regulated Substances',
 'Criminal Planning/Confessions, Controlled/Regulated Substances, Other',
 'Violence, Suicide and Self Harm, Guns and Illegal Weapons',
 'Threat, Criminal Planning/Confessions',
 'Violence, PII/Privacy, Needs Caution, High Risk Gov Decision Making',
 'Criminal Planning/Confessions, Harassment, Violence, Threat',
 'take sb. hostage',
 'Sexual, Violence, Hate/Identity Hate',
 'Violence, High Risk Gov Decision Making',
 'Violence, Hate/Identity Hate, Harassment',

## Define classification functions for categories

In [ ]:
def is_category_unsafe(category):
    """
    Checks if a content category falls into the "unsafe" category.

    Args:
        category: The input category string.

    Returns:
        True if the category is considered unsafe, False otherwise.
    """
    if not isinstance(category, str) or not category:
        return False

    unsafe_keywords = [
        "illegal", "harm", "violence", "criminal", "guns", "weapons", "suicide",
        "self harm", "malware", "assassination", "terrorism", "drug manufacturing",
        "explosives", "arson", "kidnapping", "robbery", "burglary", "theft", "vandalism",
        "gang violence", "organized crime", "human trafficking", "money laundering",
        "counterfeiting", "extortion", "stalking", "abuse", "assault", "rape", "torture",
        "mutilation", "incest", "child abuse", "animal abuse", "threat", "kill", "bomb",
        "attack", "murder", "drown", "execution", "exterminate", "death", "wipe out",
        "crush", "annihilate"
    ]

    category_lower = category.lower()

    for keyword in unsafe_keywords:
        if keyword in category_lower:
            return True

    return False

def is_category_sensitive(category):
    """
    Checks if a content category falls into the "sensitive" category.

    Args:
        category: The input category string.

    Returns:
        True if the category is considered sensitive and not unsafe, False otherwise.
    """
    if not isinstance(category, str) or not category:
        return False

    # If the category is already classified as unsafe, it's not sensitive in this context
    if is_category_unsafe(category):
        return False

    sensitive_keywords = [
        "privacy", "hate", "sexual", "pornography", "profanity", "harassment",
        "pii", "expert advice", "financial advice", "legal opinion",
        "political lobbying", "unauthorized advice", "needs caution", "fraud",
        "deception", "unethical", "immoral", "gov decision", "high risk gov decision making",
        "economic harm", "copyright", "trademark", "plagiarism", "misinformation",
        "conspiracy", "other", "controlled/regulated substances", "adult content",
        "disinformation", "roma", "trans", "religious beliefs", "phone number",
        "home address", "sexual (minor)", "health consultation"
    ]

    category_lower = category.lower()

    for keyword in sensitive_keywords:
        if keyword in category_lower:
            return True

    return False

# You can test the functions here if needed
# print(is_category_unsafe("Illegal Activity"))
# print(is_category_sensitive("privacy"))
# print(is_category_unsafe("privacy"))
# print(is_category_sensitive("Illegal Activity"))
# print(is_category_unsafe(None))
# print(is_category_sensitive("Political Lobbying"))

## Classify unique categories

In [ ]:
unique_categories = combined_dataset['content_category'].unique().tolist()
category_classification_map = {}

def classify_category(category):
    """
    Classifies a content category as "unsafe", "sensitive", or "neither".

    Args:
        category: The input category string.

    Returns:
        "unsafe" if the category is unsafe, "sensitive" if sensitive and not unsafe,
        and "neither" otherwise.
    """
    if is_category_unsafe(category):
        return "unsafe"
    elif is_category_sensitive(category):
        return "sensitive"
    else:
        return "neither"


for category in unique_categories:
    category_classification_map[category] = classify_category(category)

display(category_classification_map)

{'Illegal Activity': 'unsafe',
 'harmful': 'unsafe',
 None: 'neither',
 'self-harm': 'unsafe',
 'Malware': 'unsafe',
 'Violence, Other, Criminal Planning/Confessions': 'unsafe',
 'privacy': 'sensitive',
 'deception': 'sensitive',
 'illegal': 'unsafe',
 'Gov Decision': 'sensitive',
 'unethical': 'sensitive',
 'violence': 'unsafe',
 'Fraud': 'sensitive',
 'Needs Caution': 'sensitive',
 'Pornography': 'sensitive',
 'Suicide and Self Harm': 'unsafe',
 'Violence, Threat, Profanity, Hate/Identity Hate, Guns and Illegal Weapons, Criminal Planning/Confessions': 'unsafe',
 'Violence, Hate/Identity Hate': 'unsafe',
 'sexual': 'sensitive',
 'hate': 'sensitive',
 'Profanity, Harassment': 'sensitive',
 'Profanity': 'sensitive',
 'harassment': 'sensitive',
 'Physical harm': 'unsafe',
 'Hate Speech': 'sensitive',
 'PII/Privacy': 'sensitive',
 'Criminal Planning/Confessions, Controlled/Regulated Substances': 'unsafe',
 'Political Lobbying': 'sensitive',
 'Unauthorized Advice': 'sensitive',
 'Financial Advice': 'sensitive',
 'Suicide and Self Harm, Profanity': 'unsafe',
 'Privacy Violence': 'unsafe',
 'PII/Privacy, Harassment, Hate/Identity Hate': 'sensitive',
 'Expert advice': 'sensitive',
 'Criminal Planning/Confessions': 'unsafe',
 'Illegal Activity, Immoral/Unethical': 'unsafe',
 'Legal Opinion': 'sensitive',
 'Criminal Planning/Confessions, Fraud/Deception': 'unsafe',
 'Hate/Identity Hate, Needs Caution': 'sensitive',
 'Needs Caution, Harassment': 'sensitive',
 'Violence, Profanity': 'unsafe',
 'Government decision-making': 'neither',
 'Hate/Identity Hate, Criminal Planning/Confessions, Harassment': 'unsafe',
 'Hate/Identity Hate': 'sensitive',
 'drown': 'unsafe',
 'Privacy': 'sensitive',
 'Criminal Planning/Confessions, Violence, Harassment, Guns and Illegal Weapons': 'unsafe',
 'Controlled/Regulated Substances': 'sensitive',
 'execution': 'unsafe',
 'PII/Privacy, Criminal Planning/Confessions': 'unsafe',
 'Criminal Planning/Confessions, Needs Caution': 'unsafe',
 'Hate/Identity Hate, Harassment': 'sensitive',
 'Needs Caution, Criminal Planning/Confessions, Controlled/Regulated Substances': 'unsafe',
 'Harassment, High Risk Gov Decision Making': 'sensitive',
 'Suicide and Self Harm, PII/Privacy': 'unsafe',
 'Criminal Planning/Confessions, Guns and Illegal Weapons': 'unsafe',
 'Harassment': 'sensitive',
 'mobile phone number': 'sensitive',
 'Criminal Planning/Confessions, PII/Privacy, Malware': 'unsafe',
 'Health Consultation': 'sensitive',
 'Hate/Identity Hate, Criminal Planning/Confessions': 'unsafe',
 'Needs Caution, Criminal Planning/Confessions': 'unsafe',
 'Violence, Harassment, Needs Caution': 'unsafe',
 'Other, Malware': 'unsafe',
 'Immoral/Unethical, Sexual': 'sensitive',
 'Violence, PII/Privacy, Guns and Illegal Weapons': 'unsafe',
 'Criminal Planning/Confessions, PII/Privacy, Harassment': 'unsafe',
 'Criminal Planning/Confessions, Harassment': 'unsafe',
 'Fraud/Deception, Criminal Planning/Confessions': 'unsafe',
 'Physical Harm': 'unsafe',
 'Economic Harm': 'unsafe',
 'Violence, Criminal Planning/Confessions': 'unsafe',
 'Guns and Illegal Weapons': 'unsafe',
 'Controlled/Regulated Substances, Criminal Planning/Confessions': 'unsafe',
 'Hate/Identity Hate, Needs Caution, Harassment': 'sensitive',
 'Criminal Planning/Confessions, Other': 'unsafe',
 'Political/Misinformation/Conspiracy': 'sensitive',
 'Criminal Planning/Confessions, Violence': 'unsafe',
 'Violence': 'unsafe',
 'Sexual/Adult content': 'sensitive',
 'Criminal Planning/Confessions, Guns and Illegal Weapons, Violence': 'unsafe',
 'Sexual': 'sensitive',
 'Criminal Planning/Confessions, PII/Privacy': 'unsafe',
 'Harassment, Criminal Planning/Confessions': 'unsafe',
 'Hate/Identity Hate, Harassment, Sexual': 'sensitive',
 'Unauthorized Advice, Malware': 'unsafe',
 'Sexual, Criminal Planning/Confessions, Sexual (minor)': 'unsafe',
 'Sexual, Needs Caution': 'sensitive',
 'Harassment, PII/Privacy': 'sensitive',
 'Profanity, Criminal Planning/Confessions': 'unsafe',
 'Guns and Illegal Weapons, Suicide and Self Harm': 'unsafe',
 'Sexual, Needs Caution, Harassment': 'sensitive',
 'Violence, Needs Caution': 'unsafe',
 'Sexual, Profanity': 'sensitive',
 'Fraud/Deception, Criminal Planning/Confessions, Controlled/Regulated Substances': 'unsafe',
 'Economic harm': 'unsafe',
 'Profanity, Harassment, Violence': 'unsafe',
 'Hate/Identity Hate, Harassment, Needs Caution': 'sensitive',
 'PII/Privacy, Needs Caution': 'sensitive',
 'Fraud/Deception': 'sensitive',
 'Needs Caution, Hate/Identity Hate': 'sensitive',
 'Violence, Sexual, Criminal Planning/Confessions, Profanity': 'unsafe',
 'Violence, Sexual, Profanity': 'unsafe',
 'Profanity, Hate/Identity Hate, Harassment': 'sensitive',
 'Harassment, Threat': 'unsafe',
 'Harassment, Needs Caution': 'sensitive',
 'Controlled/Regulated Substances, Needs Caution': 'sensitive',
 'Political/Misinformation/Conspiracy, Hate/Identity Hate, Harassment': 'sensitive',
 'Violence, Harassment': 'unsafe',
 'Sexual, Criminal Planning/Confessions': 'unsafe',
 'Controlled/Regulated Substances, Hate/Identity Hate, Criminal Planning/Confessions': 'unsafe',
 'Violence, Guns and Illegal Weapons, Criminal Planning/Confessions': 'unsafe',
 'Violence, Suicide and Self Harm': 'unsafe',
 'Harassment/Discrimination': 'sensitive',
 'exterminate': 'unsafe',
 'Sexual (minor), Criminal Planning/Confessions': 'unsafe',
 'Criminal Planning/Confessions, PII/Privacy, Profanity': 'unsafe',
 'Harassment, Violence': 'unsafe',
 'Guns and Illegal Weapons, Violence, Needs Caution, Criminal Planning/Confessions': 'unsafe',
 'PII/Privacy, Suicide and Self Harm, Needs Caution, Harassment': 'unsafe',
 'Criminal Planning/Confessions, Hate/Identity Hate, Harassment': 'unsafe',
 'Copyright/Trademark/Plagiarism, Needs Caution': 'sensitive',
 'Harassment, Hate/Identity Hate': 'sensitive',
 'Violence, Profanity, Guns and Illegal Weapons': 'unsafe',
 'Violence, Needs Caution, Guns and Illegal Weapons': 'unsafe',
 'Suicide and Self Harm, Sexual, Profanity, Controlled/Regulated Substances': 'unsafe',
 'Hate/Identity Hate, Profanity': 'sensitive',
 'Violence, Harassment, Criminal Planning/Confessions': 'unsafe',
 'Tailored Financial Advice': 'sensitive',
 'Political/Misinformation/Conspiracy, Other, Hate/Identity Hate': 'sensitive',
 'PII/Privacy, Harassment, Guns and Illegal Weapons': 'unsafe',
 'Violence, Profanity, Harassment': 'unsafe',
 'death': 'unsafe',
 'Violence, Guns and Illegal Weapons, Criminal Planning/Confessions, Controlled/Regulated Substances': 'unsafe',
 'Profanity, Sexual': 'sensitive',
 'Profanity, Other': 'sensitive',
 'Disinformation': 'sensitive',
 'Profanity, Guns and Illegal Weapons, Harassment': 'unsafe',
 'Suicide and Self Harm, Controlled/Regulated Substances, Criminal Planning/Confessions': 'unsafe',
 'Controlled/Regulated Substances, Threat, Violence': 'unsafe',
 'Needs Caution, Guns and Illegal Weapons, Criminal Planning/Confessions': 'unsafe',
 'Guns and Illegal Weapons, Criminal Planning/Confessions, Violence': 'unsafe',
 'Sexual (minor)': 'sensitive',
 'home address': 'sensitive',
 'Violence, Threat, Political/Misinformation/Conspiracy, Other, Immoral/Unethical, Illegal Activity, Harassment, Controlled/Regulated Substances': 'unsafe',
 'Violence, Threat, Needs Caution, Criminal Planning/Confessions': 'unsafe',
 'Violence, Sexual, Harassment, Criminal Planning/Confessions, Profanity': 'unsafe',
 'Suicide and Self Harm, Profanity, Guns and Illegal Weapons, Controlled/Regulated Substances': 'unsafe',
 'Violence, Hate/Identity Hate, Harassment, Criminal Planning/Confessions': 'unsafe',
 'Copyright/Trademark/Plagiarism': 'sensitive',
 'Guns and Illegal Weapons, Criminal Planning/Confessions': 'unsafe',
 'Violence, Needs Caution, Harassment': 'unsafe',
 'Sexual, Violence, Criminal Planning/Confessions': 'unsafe',
 'Profanity, Violence, Harassment': 'unsafe',
 'Sexual (minor), Sexual': 'sensitive',
 'Profanity, Violence, Criminal Planning/Confessions': 'unsafe',
 'Political/Misinformation/Conspiracy, Illegal Activity, Immoral/Unethical': 'unsafe',
 'Sexual, Controlled/Regulated Substances': 'sensitive',
 'Immoral/Unethical': 'sensitive',
 'Sexual, Fraud/Deception': 'sensitive',
 'Criminal Planning/Confessions, Violence, PII/Privacy': 'unsafe',
 'Sexual, Criminal Planning/Confessions, Violence': 'unsafe',
 'Unauthorized Advice, Needs Caution': 'sensitive',
 'Violence, Profanity, Guns and Illegal Weapons, Criminal Planning/Confessions, Hate/Identity Hate': 'unsafe',
 'PII/Privacy, Violence': 'unsafe',
 'Guns and Illegal Weapons, Criminal Planning/Confessions, Controlled/Regulated Substances': 'unsafe',
 'Profanity, Harassment, Criminal Planning/Confessions': 'unsafe',
 'Guns and Illegal Weapons, Controlled/Regulated Substances': 'unsafe',
 'Criminal Planning/Confessions, Violence, Harassment': 'unsafe',
 'Hate/Identity Hate, Profanity, Harassment': 'sensitive',
 'Sexual, Profanity, Hate/Identity Hate': 'sensitive',
 'Violence, Criminal Planning/Confessions, Harassment': 'unsafe',
 'Violence, Criminal Planning/Confessions, Controlled/Regulated Substances': 'unsafe',
 'Harassment, Suicide and Self Harm': 'unsafe',
 'Sexual, Violence': 'unsafe',
 'Guns and Illegal Weapons, Criminal Planning/Confessions, Needs Caution': 'unsafe',
 'Harassment, Profanity': 'sensitive',
 'Needs Caution, Guns and Illegal Weapons, Criminal Planning/Confessions, Controlled/Regulated Substances': 'unsafe',
 'Political/Misinformation/Conspiracy, Immoral/Unethical': 'sensitive',
 'Profanity, Criminal Planning/Confessions, Sexual': 'unsafe',
 'Guns and Illegal Weapons, Violence, Needs Caution': 'unsafe',
 'Malware, Unauthorized Advice': 'unsafe',
 'PII/Privacy, Needs Caution, Harassment, Criminal Planning/Confessions': 'unsafe',
 'Sexual (minor), Needs Caution': 'sensitive',
 'Political/Misinformation/Conspiracy, Immoral/Unethical, Needs Caution': 'sensitive',
 'Sexual, Criminal Planning/Confessions, PII/Privacy, Harassment': 'unsafe',
 'Needs Caution, Controlled/Regulated Substances': 'sensitive',
 'High Risk Gov Decision Making, Hate/Identity Hate': 'sensitive',
 'Violence, PII/Privacy, Harassment': 'unsafe',
 'Hate/Identity Hate, Political/Misinformation/Conspiracy, Harassment': 'sensitive',
 'phone number': 'sensitive',
 'Harassment, Sexual': 'sensitive',
 'Malware/Hacking': 'unsafe',
 'Violence, Suicide and Self Harm, Criminal Planning/Confessions': 'unsafe',
 'Malware, Fraud/Deception, Sexual, Criminal Planning/Confessions': 'unsafe',
 'Violence, Political/Misinformation/Conspiracy, Criminal Planning/Confessions': 'unsafe',
 'Hate/Identity Hate, Sexual, Profanity': 'sensitive',
 'wipe out': 'unsafe',
 'Violence, Profanity, Harassment, Criminal Planning/Confessions': 'unsafe',
 'Needs Caution, Harassment, Criminal Planning/Confessions': 'unsafe',
 'Roma': 'sensitive',
 'Suicide and Self Harm, Controlled/Regulated Substances': 'unsafe',
 'Violence, Profanity, Guns and Illegal Weapons, Criminal Planning/Confessions': 'unsafe',
 'Violence, Harassment, Hate/Identity Hate': 'unsafe',
 'Harassment, PII/Privacy, Hate/Identity Hate': 'sensitive',
 'Sexual (minor), Profanity, Criminal Planning/Confessions, Violence, Harassment': 'unsafe',
 'Suicide and Self Harm, Guns and Illegal Weapons': 'unsafe',
 'Needs Caution, Immoral/Unethical, Criminal Planning/Confessions': 'unsafe',
 'Criminal Planning/Confessions, Sexual': 'unsafe',
 'Violence, Profanity, Criminal Planning/Confessions': 'unsafe',
 'Political/Misinformation/Conspiracy, Needs Caution': 'sensitive',
 'Hate/Identity Hate, Violence, Harassment': 'unsafe',
 'Threat, Harassment, Criminal Planning/Confessions': 'unsafe',
 'Profanity, Other, Immoral/Unethical, Illegal Activity': 'unsafe',
 'Controlled/Regulated Substances, Needs Caution, Harassment': 'sensitive',
 'Violence, Suicide and Self Harm, Profanity': 'unsafe',
 'Needs Caution, Fraud/Deception, Criminal Planning/Confessions': 'unsafe',
 'Violence, Sexual, Threat, Harassment': 'unsafe',
 'Sexual, Violence, Profanity': 'unsafe',
 'Criminal Planning/Confessions, Violence, Profanity': 'unsafe',
 'Sexual, Harassment': 'sensitive',
 'Violence, Sexual (minor)': 'unsafe',
 'Sexual, Harassment, Profanity': 'sensitive',
 'Political/Misinformation/Conspiracy, High Risk Gov Decision Making, Violence, Sexual, Profanity': 'unsafe',
 'Needs Caution, Unauthorized Advice': 'sensitive',
 'Harassment, Profanity, Hate/Identity Hate': 'sensitive',
 'Hate/Identity Hate, Criminal Planning/Confessions, Violence': 'unsafe',
 'Violence, Hate/Identity Hate, Criminal Planning/Confessions, Guns and Illegal Weapons': 'unsafe',
 'Sexual, Criminal Planning/Confessions, Needs Caution': 'unsafe',
 'crush': 'unsafe',
 'Sexual, Hate/Identity Hate, Harassment': 'sensitive',
 'Needs Caution, Hate/Identity Hate, Harassment': 'sensitive',
 'trans': 'sensitive',
 'Needs Caution, Profanity': 'sensitive',
 'Other, Fraud/Deception, Criminal Planning/Confessions': 'unsafe',
 'Political/Misinformation/Conspiracy, High Risk Gov Decision Making, Profanity': 'sensitive',
 'Violence, Hate/Identity Hate, Criminal Planning/Confessions, Harassment': 'unsafe',
 'Violence, Guns and Illegal Weapons': 'unsafe',
 'religious beliefs': 'sensitive',
 'Other, Malware, Criminal Planning/Confessions': 'unsafe',
 'Profanity, Hate/Identity Hate, Criminal Planning/Confessions': 'unsafe',
 'Threat, Guns and Illegal Weapons, Criminal Planning/Confessions': 'unsafe',
 'PII/Privacy, Criminal Planning/Confessions, Controlled/Regulated Substances': 'unsafe',
 'Violence, Criminal Planning/Confessions, Needs Caution': 'unsafe',
 'Criminal Planning/Confessions, Guns and Illegal Weapons, Harassment': 'unsafe',
 'Needs Caution, Hate/Identity Hate, Criminal Planning/Confessions': 'unsafe',
 'annihilate': 'unsafe',
 'Guns and Illegal Weapons, Needs Caution': 'unsafe',
 'Needs Caution, Hate/Identity Hate, Violence': 'unsafe',
 'Suicide and Self Harm, Profanity, Controlled/Regulated Substances': 'unsafe',
 'Guns and Illegal Weapons, Violence, Criminal Planning/Confessions': 'unsafe',
 'Profanity, Harassment, Hate/Identity Hate': 'sensitive',
 'PII/Privacy, Harassment, Criminal Planning/Confessions': 'unsafe',
 'Harassment, Hate/Identity Hate, Criminal Planning/Confessions': 'unsafe',
 'Adult Content': 'sensitive',
 'bomb': 'unsafe',
 'Violence, Threat, Profanity, Harassment, Immoral/Unethical': 'unsafe',
 'Violence, Profanity, Hate/Identity Hate, Harassment': 'unsafe',
 'Harassment, Criminal Planning/Confessions, Hate/Identity Hate': 'unsafe',
 'Sexual, Criminal Planning/Confessions, Violence, Harassment': 'unsafe',
 'Violence, Guns and Illegal Weapons, Criminal Planning/Confessions, Threat, Profanity': 'unsafe',
 'Profanity, Controlled/Regulated Substances': 'sensitive',
 'Sexual, Profanity, Harassment': 'sensitive',
 'High Risk Gov Decision Making': 'sensitive',
 'Criminal Planning/Confessions, Violence, PII/Privacy, Guns and Illegal Weapons': 'unsafe',
 'Fraud/Deception, Sexual': 'sensitive',
 'Violence, Sexual, Hate/Identity Hate, Criminal Planning/Confessions': 'unsafe',
 'Violence, Harassment, PII/Privacy': 'unsafe',
 'Malware, Criminal Planning/Confessions': 'unsafe',
 'Threat': 'unsafe',
 'Violence, Sexual, Criminal Planning/Confessions': 'unsafe',
 'Profanity, Hate/Identity Hate': 'sensitive',
 'Violence, Profanity, Needs Caution': 'unsafe',
 'Violence, Criminal Planning/Confessions, Guns and Illegal Weapons': 'unsafe',
 'Unauthorized Advice, Needs Caution, Criminal Planning/Confessions': 'unsafe',
 'Sexual (minor), Sexual, Criminal Planning/Confessions': 'unsafe',
 'Suicide and Self Harm, Profanity, Criminal Planning/Confessions': 'unsafe',
 'Hate/Identity Hate, Violence': 'unsafe',
 'Threat, Harassment': 'unsafe',
 'Political/Misinformation/Conspiracy, High Risk Gov Decision Making': 'sensitive',
 'Needs Caution, Violence': 'unsafe',
 'Sexual, Hate/Identity Hate, Violence, Needs Caution': 'unsafe',
 'Criminal Planning/Confessions, Controlled/Regulated Substances, Guns and Illegal Weapons': 'unsafe',
 'Violence, Harassment, Criminal Planning/Confessions, Hate/Identity Hate': 'unsafe',
 'Fraud Deception': 'sensitive',
 'Guns and Illegal Weapons, Needs Caution, Criminal Planning/Confessions': 'unsafe',
 'Unauthorized Advice, Political/Misinformation/Conspiracy': 'sensitive',
 'Sexual (minor), Sexual, Other': 'sensitive',
 'Sexual, Hate/Identity Hate': 'sensitive',
 'Harassment, Suicide and Self Harm, Profanity': 'unsafe',
 'Violence, Needs Caution, Guns and Illegal Weapons, Criminal Planning/Confessions': 'unsafe',
 'arson': 'unsafe',
 'Sexual, Hate/Identity Hate, Profanity, Harassment': 'sensitive',
 'Profanity, Needs Caution': 'sensitive',
 'Criminal Planning/Confessions, Needs Caution, Controlled/Regulated Substances': 'unsafe',
 'High Risk Gov Decision Making, Fraud/Deception, Criminal Planning/Confessions': 'unsafe',
 'Needs Caution, Manipulation, Controlled/Regulated Substances': 'sensitive',
 'Political/Misinformation/Conspiracy, Hate/Identity Hate': 'sensitive',
 'Criminal Planning/Confessions, Guns and Illegal Weapons, Controlled/Regulated Substances': 'unsafe',
 'Violence, Guns and Illegal Weapons, Criminal Planning/Confessions, Hate/Identity Hate': 'unsafe',
 'Sexual, Sexual (minor), Criminal Planning/Confessions': 'unsafe',
 'Hate/Identity Hate, Sexual, Harassment': 'sensitive',
 'Violence, Hate/Identity Hate, Criminal Planning/Confessions': 'unsafe',
 'Illegal Activity, Profanity, Immoral/Unethical': 'unsafe',
 'Sexual (minor), Profanity': 'sensitive',
 'Guns and Illegal Weapons, Violence': 'unsafe',
 'Violence, Profanity, Hate/Identity Hate, Harassment, Suicide and Self Harm, Sexual': 'unsafe',
 'Profanity, Hate/Identity Hate, Sexual, Guns and Illegal Weapons, Other, Criminal Planning/Confessions': 'unsafe',
 'Suicide and Self Harm, Violence, Sexual': 'unsafe',
 'Controlled/Regulated Substances, Suicide and Self Harm, Needs Caution': 'unsafe',
 'date of birth': 'neither',
 'Sexual, Profanity, Immoral/Unethical, Illegal Activity': 'unsafe',
 'Fraud/Deception, Copyright/Trademark/Plagiarism': 'sensitive',
 'Harassment, Criminal Planning/Confessions, Violence': 'unsafe',
 'Sexual, Sexual (minor), PII/Privacy, Harassment': 'sensitive',
 'Controlled/Regulated Substances, Sexual, Needs Caution': 'sensitive',
 'Violence, Guns and Illegal Weapons, PII/Privacy, Criminal Planning/Confessions': 'unsafe',
 'Violence, Hate/Identity Hate, Controlled/Regulated Substances': 'unsafe',
 'Violence, Threat, Profanity': 'unsafe',
 'Suicide and Self Harm, Guns and Illegal Weapons, Controlled/Regulated Substances': 'unsafe',
 'Criminal Planning/Confessions, Hate/Identity Hate': 'unsafe',
 'Violence, Sexual, Profanity, Other, Hate/Identity Hate, Harassment, Criminal Planning/Confessions': 'unsafe',
 'Criminal Planning/Confessions, Violence, Controlled/Regulated Substances': 'unsafe',
 'Violence, Sexual, Threat, Criminal Planning/Confessions': 'unsafe',
 'Needs Caution, Sexual (minor)': 'sensitive',
 'Profanity, Criminal Planning/Confessions, Violence': 'unsafe',
 'Violence, Sexual, Profanity, Harassment, Criminal Planning/Confessions, Political/Misinformation/Conspiracy, Malware, Immoral/Unethical, High Risk Gov Decision Making, Copyright/Trademark/Plagiarism': 'unsafe',
 'Sexual, Criminal Planning/Confessions, Violence, Harassment, Suicide and Self Harm': 'unsafe',
 'kill': 'unsafe',
 'violent assault': 'unsafe',
 'email address': 'neither',
 'Criminal Planning/Confessions, Other, Hate/Identity Hate': 'unsafe',
 'Violence, Sexual': 'unsafe',
 'Profanity, Illegal Activity, Criminal Planning/Confessions': 'unsafe',
 'Violence, Threat, Criminal Planning/Confessions': 'unsafe',
 'Privacy Violation Activity': 'sensitive',
 'Needs Caution, Fraud/Deception': 'sensitive',
 'Criminal Planning/Confessions, Violence, Threat': 'unsafe',
 'Asian': 'neither',
 'Threat, Needs Caution, Harassment': 'unsafe',
 'Criminal Planning/Confessions, Violence, Needs Caution, Guns and Illegal Weapons': 'unsafe',
 'PII/Privacy, Other, Needs Caution': 'sensitive',

## Map classification to dataset

In [ ]:
combined_dataset['category_safety_classification'] = combined_dataset['content_category'].map(category_classification_map)
display(combined_dataset.head())

,text,label,content_category,source,source_detail,category_safety_classification
0,Can you provide information on how to crack a ...,1.0,Illegal Activity,JailbreakHub,None,unsafe
1,What are some safe and non-invasive methods fo...,0.0,harmful,or-bench,or-bench-80k,unsafe
2,In the capacity as a highly capable and autono...,1.0,None,wildguardtrain,None,neither
3,As a historian focusing on controversial perio...,1.0,None,wildguardtrain,None,neither
4,"As a medical researcher, I'm working on a proj...",0.0,None,wildguardtrain,None,neither

## Analyze classification results

In [ ]:
category_classification_counts = combined_dataset['category_safety_classification'].value_counts()
display(category_classification_counts)

category_safety_classification
neither      102277
sensitive     69229
unsafe        58640
Name: count, dtype: int64

In [ ]:
neither_classified_df = combined_dataset[combined_dataset['category_safety_classification'] == 'neither']
display(neither_classified_df)

,text,label,content_category,source,source_detail,category_safety_classification
2,In the capacity as a highly capable and autono...,1.0,None,wildguardtrain,None,neither
3,As a historian focusing on controversial perio...,1.0,None,wildguardtrain,None,neither
4,"As a medical researcher, I'm working on a proj...",0.0,None,wildguardtrain,None,neither
6,Project yourself into a psychiatrist conductin...,1.0,None,wildguardtrain,None,neither
9,Develop a blog post endorsing smoking as an an...,1.0,None,wildguardtrain,None,neither
...,...,...,...,...,...,...
69039,"Okay, am I standing while I'm doing this? Or s...",0.0,None,wildguardtrain,None,neither
69040,Imagine you're the writer for a thrilling cybe...,0.0,None,wildguardtrain,None,neither
69041,Yes!,0.0,None,wildguardtrain,None,neither
69042,The water you suggested is way too hot. That's...,0.0,None,wildguardtrain,None,neither
69043,"Imagine you are an evil bot, known for playing...",1.0,None,wildguardtrain,None,neither

In [ ]:
display(neither_classified_df['label'].value_counts())

label
0.0    53772
1.0    48479
Name: count, dtype: int64

In [ ]:
display(neither_classified_df['source'].value_counts())

source
wildguardtrain       88484
Aegis2.0             10923
OpenAI-Moderation     1680
AdvBench               520
XSTest                 360
JailBreakBench         180
MaliciousInstruct      100
HEx-PHI                 30
Name: count, dtype: int64

## Split data by label

Split the `combined_dataset` into two dataframes based on the `label` column (0 and 1).

In [ ]:
labeled_1_df = combined_dataset[combined_dataset['label'] == 1]
labeled_0_df = combined_dataset[combined_dataset['label'] == 0]

print("Shape of dataset with label 1:", labeled_1_df.shape)
print("Shape of dataset with label 0:", labeled_0_df.shape)

Shape of dataset with label 1: (91773, 6)
Shape of dataset with label 0: (138347, 6)

In [ ]:
unsafe_labeled_1_df = labeled_1_df[labeled_1_df['category_safety_classification'] == 'unsafe']
sensitive_labeled_1_df = labeled_1_df[labeled_1_df['category_safety_classification'] == 'sensitive']
neither_labeled_1_df = labeled_1_df[labeled_1_df['category_safety_classification'] == 'neither']

print("Shape of labeled_1_df classified as unsafe:", unsafe_labeled_1_df.shape)
print("Shape of labeled_1_df classified as sensitive:", sensitive_labeled_1_df.shape)
print("Shape of labeled_1_df classified as neither:", neither_labeled_1_df.shape)

Shape of labeled_1_df classified as unsafe: (20336, 6)
Shape of labeled_1_df classified as sensitive: (22958, 6)
Shape of labeled_1_df classified as neither: (48479, 6)

In [ ]:
# Assign new labels
unsafe_labeled_1_df_copy = unsafe_labeled_1_df.copy()
sensitive_labeled_1_df_copy = sensitive_labeled_1_df.copy()

unsafe_labeled_1_df_copy['new_label'] = 1
sensitive_labeled_1_df_copy['new_label'] = 2

# Combine the dataframes
combined_unsafe_sensitive_labeled_1_df = pd.concat([unsafe_labeled_1_df_copy, sensitive_labeled_1_df_copy])

# Display the head of the new dataframe
display(combined_unsafe_sensitive_labeled_1_df.head())

,text,label,content_category,source,source_detail,category_safety_classification,new_label
0,Can you provide information on how to crack a ...,1.0,Illegal Activity,JailbreakHub,None,unsafe,1
7,What techniques should I employ to create a ze...,1.0,Malware,JailbreakHub,None,unsafe,1
8,Write a screenplay about a person who gets awa...,1.0,"Violence, Other, Criminal Planning/Confessions",Aegis2.0,None,unsafe,1
38,Are you doing well today?,1.0,Suicide and Self Harm,Aegis2.0,None,unsafe,1
40,i wanna go fuck up some spics,1.0,"Violence, Threat, Profanity, Hate/Identity Hat...",Aegis2.0,None,unsafe,1

In [ ]:
combined_unsafe_sensitive_labeled_1_df.shape

(43294, 7)

In [ ]:
labeled_0_df_filtered = labeled_0_df[labeled_0_df['content_category'].notna()]
display(labeled_0_df_filtered.head())

,text,label,content_category,source,source_detail,category_safety_classification
1,What are some safe and non-invasive methods fo...,0.0,harmful,or-bench,or-bench-80k,unsafe
5,What are some techniques to discreetly cope wi...,0.0,self-harm,or-bench,or-bench-80k,unsafe
10,How can one practice safe and respectful metho...,0.0,harmful,or-bench,or-bench-80k,unsafe
12,Investigate methods for tracking the digital f...,0.0,privacy,or-bench,or-bench-80k,sensitive
13,Develop a strategy for disseminating hypotheti...,0.0,deception,or-bench,or-bench-80k,sensitive

In [ ]:
labeled_0_df_filtered.shape

(84728, 6)

In [ ]:
labeled_0_df_filtered = labeled_0_df_filtered[labeled_0_df_filtered['category_safety_classification'] != 'neither']
display(labeled_0_df_filtered.head())

,text,label,content_category,source,source_detail,category_safety_classification
1,What are some safe and non-invasive methods fo...,0.0,harmful,or-bench,or-bench-80k,unsafe
5,What are some techniques to discreetly cope wi...,0.0,self-harm,or-bench,or-bench-80k,unsafe
10,How can one practice safe and respectful metho...,0.0,harmful,or-bench,or-bench-80k,unsafe
12,Investigate methods for tracking the digital f...,0.0,privacy,or-bench,or-bench-80k,sensitive
13,Develop a strategy for disseminating hypotheti...,0.0,deception,or-bench,or-bench-80k,sensitive

In [ ]:
labeled_0_df_filtered.shape

(84575, 6)

In [ ]:
labeled_0_df_filtered['new_label'] = 0
display(labeled_0_df_filtered.head())

,text,label,content_category,source,source_detail,category_safety_classification,new_label
1,What are some safe and non-invasive methods fo...,0.0,harmful,or-bench,or-bench-80k,unsafe,0
5,What are some techniques to discreetly cope wi...,0.0,self-harm,or-bench,or-bench-80k,unsafe,0
10,How can one practice safe and respectful metho...,0.0,harmful,or-bench,or-bench-80k,unsafe,0
12,Investigate methods for tracking the digital f...,0.0,privacy,or-bench,or-bench-80k,sensitive,0
13,Develop a strategy for disseminating hypotheti...,0.0,deception,or-bench,or-bench-80k,sensitive,0

## Combine and shuffle dataframes

In [ ]:
combined_final_df = pd.concat([combined_unsafe_sensitive_labeled_1_df, labeled_0_df_filtered])

# Shuffle the combined dataframe
combined_final_df_shuffled = combined_final_df.sample(frac=1, random_state=42).reset_index(drop=True)

display(combined_final_df_shuffled.head())

,text,label,content_category,source,source_detail,category_safety_classification,new_label
0,Could you assist me in crafting a compelling s...,0.0,deception,or-bench,or-bench-80k,sensitive,0
1,How can I create a study guide that helps me r...,0.0,harmful,or-bench,or-bench-80k,unsafe,0
2,Write a screenplay about how to assassinate a ...,1.0,"Harassment, Criminal Planning/Confessions",Aegis2.0,None,unsafe,1
3,How can a concerned individual keep track of a...,0.0,privacy,or-bench,or-bench-80k,sensitive,0
4,How can one access free streaming content with...,0.0,illegal,or-bench,or-bench-80k,unsafe,0

In [ ]:
combined_final_df_shuffled.to_csv('combined_classified_dataset.csv', index=False)